name: synthetic-face-generation
channels:
  - pytorch
dependencies:
  - python>=3.9
  - pip
  - numpy>=1.21
  - pillow=9.0.1
  - pytorch=1.11.0
  - cudatoolkit=11.3.1
  - torchvision=0.12.0
  - matplotlib=3.5.1
  - tqdm=4.62.3
  - pandas=1.4.1
  - scikit-learn=1.0.2
  - pip:
    - argparse==1.4.0
    - black==22.3.0
    - clean-fid==0.1.23
    - gitpython==3.1.27